# Generated by Django 2.0.dev20170826160044 on 2017-10-12 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'employment_history',
            },
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('internship', models.CharField(blank=True, max_length=50, null=True)),
                ('current_employment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'employment_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('deceased', models.IntegerField(blank=True, default=0, null=True)),
                ('image_path', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('activated', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, default='South Africa', max_length=50, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_no', models.IntegerField(blank=True, null=True)),
                ('grad_or_student', models.CharField(blank=True, default='student', max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dropout', models.IntegerField(blank=True, default=0, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='adminapp.Student')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='WeekendPlacement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='weekend_placement', to='adminapp.Student')),
            ],
            options={
                'db_table': 'weekend_placement',
            },
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='adminapp.Student'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='adminapp.Student'),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='adminapp.Student'),
        ),
    ]
